### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by MatthewCaseres** [RunestoneInteractive/overview#19]
The page at https://runestone.academy/runestone/books/published/overview/index.html has a link to https://runestone.academy/runestone/static/instructorguide/WritingExercises/toctree.html which is broken.

**Comment by areskeldi** [comment]
Seems like the issue has been resolved, the _Documentation on how to do that_ link within the https://runestone.academy/runestone/books/published/overview/index.html page leads to https://runestone.academy/runestone/books/published/overview/index.html now
