### ISSUE TITLE
Long page

### ISSUE THREAD

**Issue by bjones1** [RunestoneInteractive/overview#7]
The main page (`overview.rst`) is really long. What do you think of dividing into multiple pages?
- Activecode
- CodeLens, ShowEval, etc.
- Traditional questions (multiple choice, fitb, parsons, etc)
- Other (disqus, youtube, polls, audio tour, etc)
- Formatting (reveal, tabbed, general advice on reST)

**Comment by bnmnetp** [comment]
I would be OK with breaking it up into some smaller pages

**Comment by bjones1** [comment]
Sounds good. I'll work on it after you accept the existing PR.

**Comment by bnmnetp** [comment]
Fixed
